/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    ":widepeepoHappy:": ":widepeepoHappy:",
    "\"Can't Empty The Tank\"": "“无法清空水箱”",
    "\"Gotta Empty The Tank\"": "“得清空水箱”",
    "\"Shut Up B**ch\"": "\"闭嘴靓仔\"",
    "\"The Perfect Concentration\"": "《完美的专注》",
    "A fun little periodic table:": "一个有趣的小元素周期表：",
    "Acamaeda,": "阿卡梅达，",
    "Ah sh*t, here we go again.": "啊sh*t，我们又来了。",
    "all forms of xp": "所有形式的 xp",
    "Avogadro's Constant": "阿伏伽德罗常数",
    "Black lung.": "黑肺。",
    "Break the current max capacity.": "打破当前最大容量。",
    "Click Deflate at 497L of Helium Gas or higher.": "单击 497L 或更高的氦气放气。",
    "Credits:": "学分：",
    "Decode with Base64 for answer: U3BhbSBjbGljayBvbiBob2xkIGJ1dHRvbiB3ZWlyZG8u": "使用 Base64 解码以获得答案：U3BhbSBjbGljayBvbiBob2xkIGJ1dHRvbiB3ZWlyZG8u",
    "Doctor Who???": "神秘博士？？？",
    "Element(s)": "元素）",
    "Escapee,": "逃犯，",
    "Expenses/day:": "费用/天：",
    "Fill the bar 3 times without the multiplier dropping to 0.2.": "填充条形图 3 次，但乘数不会降至 0.2。",
    "Fill up the bar around 5 times with a 1.1 Hydrogen Multiplier. Now go to the gym.": "使用 1.1 氢倍增器将条形填充大约 5 次。现在去健身房。",
    "Gassed Up": "气喘吁吁",
    "Get 6.022e23. Nothing else is important. Nope.": "得到 6.022e23。其他什么都不重要。没有。",
    "Get Achievement 4": "获得成就 4",
    "Get full automation of Hydrogen layer.": "实现氢气层的全自动化。",
    "Get the second element.": "获得第二项。",
    "Health multiplies": "健康倍增",
    "Health:": "健康：",
    "Here you will advance from element to element until I decide to stop. That's about it, not much else to say...There's save files under this if you want to skip a section or your savefile gets corrupted.": "在这里，您将逐个元素前进，直到我决定停止。就是这样，没什么好说的……如果你想跳过一个部分或者你的保存文件被损坏，下面有保存文件。",
    "High-Pitched Frequency": "高音频率",
    "Hold over 1k Hydrogen Gas.": "保持超过 1k 氢气。",
    "Hydrogen": "氢",
    "Hydrogen Automaton": "氢自动机",
    "Hydrogen Gas": "氢气",
    "Hydrogen increases Hydrogen Power gain by 0": "氢气使氢气能量增益增加 0",
    "Hydrogen Tank": "氢气罐",
    "If you can't get it normally anymore or don't understand how to get it.": "如果您无法正常获取或不知道如何获取。",
    "Income/day:": "收入/天：",
    "incremental_gamer,": "增量玩家，",
    "It's Always Been One Step Forward And Two Steps Back.": "它总是前进一步，后退两步。",
    "Jakub,": "雅库布，",
    "JJP.": "J.P。",
    "Maybe you'll fix your past mistakes.": "也许你会改正你过去的错误。",
    "Mining waste into the ocean.": "将废物开采到海洋中。",
    "Money talks.": "有钱能使鬼推磨。",
    "NEET": "尼特",
    "Net/day:": "净/天：",
    "No Hydrogen?": "没有氢气？",
    "NOOOOOOOOOOOOOOOOOOOOO WAAAAAAAAY!?!@@#@#": "NOOOOOOOOOOOOOOOOO WAAAAAAAAY!?!@@#@#",
    "Per": "Per",
    "Produce 10k Total Hydrogen Gas.": "生产 10k 总氢气。",
    "Produce Hydrogen Gas on hover.": "悬停时产生氢气。",
    "Req: 0 / 1.00 Hydrogen Power": "要求：0 / 1.00 氢能",
    "Restpritory damage.": "残损。",
    "Save files:": "保存文件：",
    "Savefiles": "保存文件",
    "SCROLL_WHEEL": "滚轮",
    "smiley,": "笑脸，",
    "Son of a GLITCH": "故障之子",
    "Spend over 201 ticks with extra text on.": "花费超过 201 个刻度和额外的文本。",
    "Suffer": "痛苦",
    "Surf surf, surf surf crazy.": "冲浪冲浪，冲浪冲浪疯狂。",
    "Tedious work eh?.": "乏味的工作是吗？",
    "Thacker Pass lithium mine.": "Thacker Pass 锂矿。",
    "This is a periodic table tree and it all starts with hydrogen because of its- well, I guess it's atomic properties or something. Anyway, start producing some hydrogen gas so we can convert it into energy or something.": "这是一个元素周期表树，它都是从氢开始的，因为它——嗯，我猜它是原子属性什么的。无论如何，开始生产一些氢气，这样我们就可以将其转化为能量或其他东西。",
    "Unlock the third element.": "解锁第三个元素。",
    "v1.6.5": "v1.6.5",
    "Welcome To The Periodic Table Tree": "欢迎来到元素周期表树",
    "widepeepoHappy": "widepeepo快乐",
    "Your First Element!": "你的第一个元素！",
    "Unlocks a button to shut off some text. Turns on others (;": "解锁按钮以关闭某些文本。 打开其他 (;",
    "OFF: Turning off text.": "关：关闭文本。",
    "ON: Turning on text.": "开：打开文本。",
    "2x Hydrogen Tank Capacity. Also unlock upgrades.": "2x 氢气罐容量。 还解锁升级。",
    "Add 1 to the Hydrogen Gas base": "氢气基数加 1",
    "Buy max Hydrogen.": "购买最大值的氢。",
    "Heisenburg": "海森堡",
    "Hydrogen Gas gain is raised to the power of 2.": "氢气增益提高到 2。",
    "Hydrogen's Based": "氢的基数",
    "Hydrogen's Gassed Up": "氢气提升",
    "Add 2 more to the base of Hydrogen Gas.": "在氢气的基础上再增加 2 。",
    "Hydrogen's Bonding": "氢键结合",
    "Currently:": "当前：",
    "Get a 2nd Hydrogen tank. Keep cost.": "获得第二个氢气罐。 保持成本。",
    "Hydrogen Gas boosts Hydrogen Gas. (Must have 6 Hydrogen Upgrades.)": "氢气增强氢气。 （必须有 6 次氢升级。）",
    "Hydrogen Power boosts Hydrogen Gas.": "氢能提升氢气。",
    "Hydrogen's Expanding": "氢的膨胀",
    "Hydrogen's Powering Up": "氢能提升",
    "Hydrogen's Half Lifed": "氢半衰期",
    "Hydrogen upgrades on this row cut Hydrogen cost, but Hydrogen Tank capcity is doubled.": "这一排的氢气升级降低了氢气成本，但氢气罐容量增加了一倍。",
    "Hydrogen's Hilarity": "氢的欢闹",
    "Unlock Helium. Keep cost.": "解锁氦。 保留成本。",
    "Another gas at SATP. I've got uh, um, some balloons for uh, um, for a party. Just go ahead and start inflating them once you can.": "SATP 的另一种气体。 我有呃，呃，一些气球，呃，呃，一个派对。 只要有可能，就继续给它们充气。",
    "Helium": "氦",
    "Keep 1 Hydrogen milestone per reset.": "每次重置保持 1 个氢里程碑。",
    "Keep 1 Hydrogen upgrade per reset.": "每次重置保持 1 个氢升级。",
    ". Keep Cost.": ". 保持成本.",
    "30x more Lithium from Lepoidolite per rocket.": "每枚火箭从锂云母中提取 30 倍以上的锂。",
    "I am not turning down the money! I am turning down you! You get it? I want nothing to do with you! Ever since I met you, everything I ever cared about is gone! Ruined, turned to s**t, dead, ever since I hooked up with the great Heisenberg!": "我不会拒绝这笔钱！ 我拒绝你！ 你明白吗？ 我不想和你有任何关系！ 自从遇见你，我在乎的一切都烟消云散了！ 毁了，变成了狗屎，死了，自从我迷上了伟大的海森堡！",
    "\":gwa:\"": "\":gwa:\"",
    "\"Cancer\"": "\“癌症\”",
    "\"Dwarf Planet\"": "\“矮行星\”",
    "\"Earthy Mulch\"": "“泥土覆盖物”",
    "\"Eggs Benedict\"": "班尼迪克蛋",
    "\"Gas Giant\"": "“气体巨人”",
    "\"Hell on Earth\"": "\“人间地狱\”",
    "\"Home\"": "\“家\”",
    "\"Ice Giant\"": "“冰巨人”",
    "\"Luminary\"": "\"发光的\"",
    "\"Morning Star and Evening Star\"": "《晨星与晚星》",
    "\"Once In A Blue Moon\"": "《蓝月》",
    "\"Planet of MultiSplendor\"": "“多光之星”",
    "\"Red Planet\"": "《红色星球》",
    "\"Ringed Planet\"": "“环状行星”",
    "\"Smaller Jupiter\"": "“小木星”",
    "\"Swift Planet\"": "“迅捷星球”",
    "\"That's not a Planet!\"": "“那不是行星！”",
    "\"The Big Blue\"": "《大蓝》",
    "\"Tycho Brahe\"": "“第谷布拉赫”",
    "\"Warm Jupiter\"": "《温暖的木星》",
    "Gold Trophy/Under 100 ticks": "金奖杯/低于 100 滴答",
    "Good Manners": "有礼貌",
    "Greatly reduce the Helium requirement exponent. Helium now multiplies Helium Expunged gain. Helium Gas no longer has its gas constantly decreasing. Keep 50% of cost.": "大大降低氦需求指数。氦气现在乘以氦气清除增益。氦气不再有它的气体不断减少。保留50%的成本。",
    "Guess. Jk, makes Beryllium Scrap to Plate converter cost nothing.": "猜测。 Jk，使铍废料到板转换器不花费任何成本。",
    "Haha, That Last Upgrade Only Made Things Harder!": "哈哈，最后一次升级只会让事情变得更难！",
    "Haumea": "豪美亚",
    "Have The Maxmum Of All Rocketship Parts": "拥有所有火箭飞船零件的最大值",
    "Have Upgrade \"Hydrogen's Lightness\"": "升级“氢之轻”",
    "Have Upgrade \"Thermal Decomposition\"": "有升级“热分解”",
    "Health": "健康",
    "Heavily reinforced doors, bullet proof glass and many bystanders. High risk, high reward": "重型强化门，防弹玻璃和许多旁观者。高风险，高回报",
    "Helium \"Leak Detection\"": "氦气“泄漏检测”",
    "Helium also boosts Helium Expunged gain by adding 5,064": "Helium 还通过增加 5,064 来提高 Helium Expunged 增益",
    "Helium hardcap is removed. Hydrogen Tank cap is decreased.": "氦硬盖被移除。氢罐盖减少。",
    "Helium Hydride Corrosion!": "氢化氦腐蚀！",
    "Helium Mutiplier is now 0, same with Helium.": "氦乘数现在为 0，与氦相同。",
    "Homeless": "无家可归",
    "Hydrogen Multiplier falls slower but increase tank capacity by 1 million times. Lose all your Helium": "氢气倍增器下降速度较慢，但​​将储罐容量增加 100 万倍。失去所有的氦气",
    "Hydrogen Multiplier Tank": "氢倍增器罐",
    "Hydrogen Mutiplier now starts at 0.": "氢倍增器现在从 0 开始。",
    "Hydrogen Tank capacity is much lower but so is the Hydrogen Multiplier cap.": "氢气罐容量要低得多，但氢气乘数上限也是如此。",
    "Hydrogen's Detonation": "氢气爆炸",
    "Hydrogen's Embrittled": "氢脆",
    "Hydrogen's Enthalpy Of Combustion": "氢的燃烧焓",
    "Hydrogen's Lightness": "氢的轻盈",
    "Hydrogen's Tritium": "氢的氚",
    "I'm Floatingggg.": "我是浮动的ggg。",
    "If Quizzes": "如果测验",
    "Improve The Diamond Hand Saw Overall.": "整体改进金刚石手锯。",
    "Improve your artillery of weapons and tools to pull off heists with higher stakes.": "改进您的武器和工具大炮，以完成更高风险的抢劫。",
    "Increase Ballon Capacity and reduce image scaling.": "增加气球容量并减少图像缩放。",
    "Increase Balloon capcity and Helium Gas Expunged rate.": "增加气球容量和氦气清除率。",
    "Increase Helium Gas Inflate and Deflate gain.": "增加氦气充气和放气增益。",
    "Increase Hydrogen Multiplier cap but Hydrogen Gas gain is divided on an exponent of how large the multiplier is. The middle has a sweet spot.": "增加氢气乘数上限，但氢气增益除以乘数有多大的指数。中间有一个甜蜜点。",
    "Inert Gas Asphyxiation: Capital Punishment Edition.": "惰性气体窒息：死刑版。",
    "Inventory": "存货",
    "It's about drive, it's about power, we stay hungry, we devour. Put in the work, put in the hours and take what's ours.": "这是关于驱动力，这是关于力量，我们保持饥饿，我们吞噬。投入工作，投入时间，拿走我们的。",
    "Janssen": "詹森",
    "Jewelry Store": "珠宝店",
    "Job Experience": "工作经验",
    "Job xp": "工作经验",
    "Job Xp": "工作经验",
    "Jobs": "工作",
    "Jupiter": "木星",
    "Keep 1 upgrade, auto 1 planet, and keep 10 Beryllium Plate buyables per reset. Toggle autobuy planets.": "每次重置保留 1 次升级，自动 1 颗行星，并保留 10 个铍板可购买物品。切换自动购买行星。",
    "Keep all rocketship part buyables. Also keep both milestones.": "保留所有可购买的火箭飞船部件。同时保留两个里程碑。",
    "Keep all rocketships.": "保留所有火箭飞船。",
    "Keep everything.": "保留一切。",
    "Keep screw you. Keep cost.": "继续坑你。保留成本。",
    "Knock Knock": "敲敲",
    "Layer Animations: Enabled": "图层动画：启用",
    "Le Universe": "宇宙",
    "Learn the art of persuasion. Have a silver tongue and watch as your expenses trickle away.": "学习说服的艺术。说白了，看着你的开支慢慢流走。",
    "Level": "等级",
    "LI = Light,  HeH = Helium Hydride, UN = Unkown, WC = Water Cloud, DI = Diamond, gwa = gwa, LA = Laser, DR = Dirt, EG = Egg.": "LI = 光，HeH = 氢化氦，UN = 未知，WC = 水云，DI = 钻石，gwa = gwa，LA = 激光，DR = 污垢，EG = 鸡蛋。",
    "Lipperhey": "利珀海",
    "Live until 70 years. You can \"reset\" yourself when you choose to do so (past 30 years, hotkey is D).": "活到70岁。当您选择这样做时，您可以“重置”自己（过去 30 年，热键是 D）。",
    "Low Quality: Disabled": "低质量：已禁用",
    "Lower cost of the first two buyables by subtacting 500,000 but set there buyable amounts to 1 and cost scales much higher.": "通过减去 500,000 来降低前两个可购买的成本，但将可购买的数量设置为 1，并且成本会更高。",
    "MainTab": "主选项卡",
    "Your own personal lacky. Not that they respect or anything. Infact, they fear you. For the pay that they receive, they feel as though they are stuck in purgatory between quitting and dying to another one of your mandatory 8 hour work session.": "你自己的私人走狗。 不是他们尊重或其他任何东西。 事实上，他们害怕你。 对于他们收到的报酬，他们觉得自己好像被困在炼狱之间，在辞职和死于另一个强制性的 8 小时工作会议之间。",
    "An inprint of your success. Lavish rooms, decadent hallways, marble tiling. What's not to love? You can even buy friends if you want!": "你成功的印记。豪华的房间，颓废的走廊，大理石瓷砖。不去爱的种种？如果你愿意，你甚至可以买朋友！",
    "Assistant": "助手",
    "Associate": "联系",
    "Carbon Fragments": "碳碎片",
    "Cardboard Box": "纸板箱",
    "Chow down on mind games for breakfast. Understand the other with a single glance. Know what they will do and inturn save yourself some time. Intelligence comes at a cost however.": "吃早餐的智力游戏。一眼就能理解对方。知道他们会做什么，从而为自己节省一些时间。然而，情报是有代价的。",
    "Deep in the wooded forest lies a oak wood shack stained by time. The musky smell waftes over you as you take a look at your new home.": "在茂密的森林深处，有一间被岁月染红的橡木小屋。当你看看你的新家时，麝香的气味飘在你身上。",
    "Dummy Xp": "虚拟 Xp",
    "Encyclopedia": "百科全书",
    "Fresh off the market, this house can easily support 8 people, though you probably don't have any friends. Gaze over the wooden balcony and feel the height of a second floor!": "刚从市场上下来，这所房子可以轻松养活 8 个人，虽然你可能没有任何朋友。凝视木制阳台，感受二楼的高度！",
    "Friend": "朋友",
    "Mansion": "大厦",
    "Merged House": "合并的房子",
    "of": "",
    "Off": "关",
    "On": "开",
    "Paused.": "暂停。",
    "Read through a variety of encyclopedias in order to strengthen your knowledge boosting your comprehension on specific skills.": "通读各种百科全书，以加强您的知识，提高您对特定技能的理解。",
    "Rough start huh?": "粗略的开始吧？",
    "Shop": "商店",
    "Skill": "技能",
    "Skills": "技能",
    "Snake, snaaaaaake!": "蛇，snaaaaaake！",
    "Thief Xp": "小偷经验",
    "Wit": "Wit",
    "Wooden Shack": "木棚屋",
    "Year: 26 Day: 104": "年：26 天：104",
    "You bought a friend, simple as that.": "你买了一个朋友，就这么简单。",
    "You'll die at 30 years, view MainTab for Updates": "你将在 30 岁时死去，查看 MainTab 以获取更新",
    "On a dark and gloomy night, you arise from the shadows overlooking the establishment. It's layered with security camera's, security guards and security doors. The chance of success is slim but rewards are plentiful. Will conquer the bank, or will you die trying?": "在一个漆黑阴沉的夜晚，你从阴影中升起，俯瞰整个建筑。 它与安全摄像头，保安人员和安全门分层。 成功的机会渺茫，但回报丰厚。 你会征服银行，还是会死去尝试？",
    "Bank Heist": "银行抢劫",
    "CEO": "首席执行官",
    "Devise executable plans for your theiving ways.": "为您的盗窃方式制定可执行的计划。",
    "Dummy": "假人",
    "Easier than stealing candy from a baby!": "比从婴儿那里偷糖果还容易！",
    "Executive Vice President": "执行副总裁",
    "Expenses": "花费",
    "Find comfort within who you are. Understand that not everyday has to be work filled. Peace comes to those who embrace it.": "在你是谁中找到安慰。明白，不是每天都必须被工作填满。和平会降临在拥抱它的人身上。",
    "Focus": "重点",
    "Full-time Miner": "全职矿工",
    "Gas Station": "加油站",
    "Max Level": "最高等级",
    "Mine Manager": "矿山经理",
    "of Carbon": "碳的",
    "of Carbon Fragments": "碳碎片",
    "of Carbon Fragments =": "碳碎片 =",
    "Ore/day": "小时/天",
    "Part-time Miner": "兼职矿工",
    "Persuasion": "劝说",
    "Pickpocket": "扒手",
    "Relaxation": "松弛",
    "Robbing a gas station is quite the step up from people's pockets wouldn't you say. With it comes much risk however.": "你不会说，抢劫加油站是从人们的口袋里冒出来的一大步。然而，随之而来的风险也很大。",
    "Skill xp": "技能经验",
    "The key is to concentrate. Ready your mind as you research and experiment. The worst yield must always be expected.": "关键是要专心。在研究和实验时做好准备。必须始终预期最差的产量。",
    "Thief Rewards": "小偷奖励",
    "Thieving Tatics": "盗窃战术",
    "Weapons/Tools": "武器/工具",
    "Wow Mr. Krabs has you working at $50 an hour! When I started working here I had to pay him $100 an hour.": "哇先生螃蟹让你以每小时 50 美元的价格工作！当我开始在这里工作时，我不得不每小时付给他 100 美元。",
    "Xp Left": "Xp 左",
    "Xp/day": "Xp/天",
    "You cannot hold any more items.": "您不能再持有任何物品。",
    "You have now been fully integrated into the company.": "你现在已经完全融入了公司。",
    "You now hold a major amount of power in the comapany. You help keep effeciency of the mines to the highest percent and answer only to the higher ups.": "你现在在公司拥有很大的权力。您帮助将矿山的效率保持在最高百分比，并且只对上级负责。",
    "You'll die at 30 years, view the MainTab for Updates": "您将在 30 岁时死去，查看 MainTab 以获取更新",
    "You're done with all the riff raff and have now been promoted to a management position!": "你已经完成了所有的 riff raff，现在已经被提升为管理职位！",
    "You're the boogeyman. When workers look up at you, all they see is; \"Get back to work!\" You only give respect to those who deserve it. Those who grovle at your feet, otherwise they're not worth your time.": "你是妖怪。当工人抬头看着你时，他们看到的只是； “回去工作吧！”你只尊重值得的人。那些在你脚下卑躬屈膝的人，否则他们不值得你花时间。",
    "And What Do You Get?": "你得到什么？",
    "Another Day Older and You're Deeper In Debt": "再大一天，你的债务就更深了",
    "Astroid Destroyer": "星体驱逐舰",
    "Become A Monster": "成为怪物",
    "Black Lung Again?": "又是黑肺？",
    "Build a \"rocketship.\"": "建造“火箭飞船”。",
    "Carbon Copied": "碳复印",
    "Colonization Is Complicated": "殖民是复杂的",
    "Destroy the final meteorite": "摧毁最后的陨石",
    "Do what they are asking for.": "做他们要求的。",
    "Fly Me To The Moon": "带我去月球",
    "Get 1 Rainbownium": "获得 1 个彩虹",
    "Get 10 Rocketships": "获得 10 艘火箭飞船",
    "Get 100 Molten Liquid Iron": "获得 100 熔化的液态铁",
    "Get 1g of Plutonium": "获得 1g 钚",
    "Get Boron Automation": "获取硼自动化",
    "Get CEO Level 10": "获得 CEO 级别 10",
    "Get CEO Level 2": "获得 CEO 2 级",
    "Get Full-time Miner Level 50": "获得全职矿工 50 级",
    "Get Jewelry Store Level 11": "获得珠宝店 11 级",
    "Get Pickpocket Level 10": "获得扒手等级 10",
    "Get the Golden Trophy.": "获得金奖杯。",
    "Get three engine nozzles.": "获得三个发动机喷嘴。",
    "Get through 50% of the riddle.": "完成 50% 的谜题。",
    "Get Upgrade, \"Organic Matter\"": "获得升级，“有机物”",
    "Get Upgrade, \"Rapid Decompression\"": "获取升级，“快速减压”",
    "Get Upgrade, \"Thermal Decomposition\"": "获得升级，“热分解”",
    "Getting Old...": "变老...",
    "Goodbye Fair Prices": "再见公平价格",
    "Goodbye Safety Goggles": "再见安全护目镜",
    "Goodbye Safety Nets": "再见安全网",
    "Goodbye Small Businesses": "再见小企业",
    "Half The Riddle, Half The Time": "一半的谜，一半的时间",
    "Have 1e9 Boron": "有 1e9 硼",
    "Have 2 Electric Diamond Hand Saw Parts": "有 2 个电动金刚石手锯零件",
    "Have 3 Prisms": "有 3 个棱镜",
    "Have 3 Rocketships": "拥有 3 艘火箭飞船",
    "Have 40 total Beryllium Plates.": "总共有 40 个铍板。",
    "Have 5 elements": "有5个元素",
    "Have 7 Boron Resets": "有 7 次硼重置",
    "Have three Boron upgrades": "进行三个硼升级",
    "Have upgrade \"CVD\"": "有升级“CVD”",
    "I Owe My Soul To The Company Store": "我的灵魂归功于公司商店",
    "I Own The Galaxy": "我拥有银河",
    "I Own You": "我欠你的",
    "Literally Grinding": "字面研磨",
    "Lucky Number Nitrogen?": "幸运数字氮？",
    "Master C- Thief": "C大师-小偷",
    "Nitrogen Chemical Reactions": "氮化学反应",
    "Nitrogen Decay": "氮衰变",
    "Nitrogen Expansion": "氮气膨胀",
    "Nitrogen Nimbility": "氮气灵活性",
    "No, This Is Not Vorona": "不，这不是沃罗纳",
    "Nuclear Magnetic Resonance": "核磁共振",
    "Obtain the fourth element.": "获得第四个元素。",
    "Petty Theft or Grand Theft Carbon?": "小偷小摸还是大盗碳？",
    "Please play Progress Knight. It's way better than this layer.": "请玩进度骑士。比这一层好多了。",
    "Rainbow's Are Forever": "彩虹永远",
    "Rejuvenated": "焕然一新",
    "Reset Carbon Layer": "重置碳层",
    "Rolling In The Dough": "在面团里滚",
    "Saint Peter Don't You Call Me 'Cause I Can't Go": "圣彼得你别叫我因为我不能走",
    "Something's Brewing": "有什么东西在酝酿",
    "The 7th Element rests in your hands.": "第七元素掌握在你的手中。",
    "The Rat Race": "老鼠赛跑",
    "The Rich Made Obedient": "富人听话",
    "The sixth element must be yours": "第六元素一定是你的",
    "They're At Your Door": "他们在你家门口",
    "They're Onto You": "他们在你身上",
    "This Is Literal Cancer": "这是真正的癌症",
    "Time Is Of The Essence": "时间就是生命",
    "Unlock The Workshop": "解锁车间",
    "Wait, That's A C-": "等等，那是C-",
    "Work for 20 Years": "工作20年",
    "You increase your yearly income.": "你增加了你的年收入。",
    "You Load Sixteen Tons": "你装载十六吨",
    "You've made life hell for others.": "你把别人的生活变成了地狱。",
    "Mines": "矿山",
    "Portal": "传送门",
    "Silicon": "硅",
    "You have no active portals.": "您没有激活的传送门。",
    "Automate Helium Inflate and Deflate. Also unlock a Lepoidolite. Reset Lithium and remove its button.": "自动化氦气充气和放气。同时解锁一个锂云石。重置锂并移除其按钮。",
    "Buy a factory.": "买工厂。",
    "Completion reward: Double Hydrogen Gain.": "完成奖励：双倍氢气增益。",
    "Completion reward: Double mining speed.": "完成奖励：双倍挖矿速度。",
    "Completion reward: Double Rubidium gain.": "完成奖励：双倍铷增益。",
    "Completion reward: Unlock challenges.": "完成奖励：解锁挑战。",
    "Completion reward: Unlock new ore.": "完成奖励：解锁新矿石。",
    "Double Helium generation.": "双氦生成。",
    "Find a portal?": "找门户？",
    "Find more ore.": "找到更多矿石。",
    "Hire a worker.": "雇用一名工人。",
    "Increase stock market shares.": "增加股票市场份额。",
    "Increases mining speed by 1% per amount.": "每数量增加 1% 的挖掘速度。",
    "Increases the amount of Hydrogen from mineral by 10% per amount.": "每增加 10% 的矿物氢气量。",
    "Increases the chance of getting Lithium by 1% per amount.": "每数量增加 1% 获得锂的几率。",
    "Increases the chance of getting Rubidium by 1% per amount.": "每增加 1% 获得铷的几率。",
    "Keep 1 Helium milestone per reset. Get rid of wideness stuff.": "每次重置保持 1 个氦里程碑。摆脱广度的东西。",
    "Keep 1 Helium upgrade per reset. Also unlock Helium auto generation. Thin balloon (:<.": "每次重置保持 1 次氦升级。同时解锁氦气自动生成。细气球 (:<.",
    "Keep 20 resets.": "保持 20 次重置。",
    "Lithium": "锂",
    "Unlocks Lithium challenges. Must have all others at max to get this.": "解锁锂挑战。必须让所有其他人都达到最大值才能得到这个。",
    "Use better equipment.": "使用更好的设备。",
    "We've struck Lithium! I'll- I'll be able to- We'll be able to make phones and electric cars with them. All ya gotta do is mine that Lepoidolite over there. Yeah, I'm gonna be rich!": "我们击中了锂！我会——我会——我们可以用他们制造手机和电动汽车。你要做的就是我那边的锂云石。是的，我要发财了！",
    "Reviews": "评论",
    "1 in 200 per Gaston County Lepoidolite.": "每 200 个加斯顿县锂云石中有 1 个。",
    "Link To Create A Review:": "创建评论的链接：",
    "Reviews Of The Periodic Table Tree": "元素周期表树的评论",
    "The Periodic Table Tree: Save Files": "元素周期表树：存档文件",
    "Automate multiplier button and resetting Hydrogen resets nothing. Increase Inflation and Deflation rate.": "自动乘数按钮和重置氢气不会重置任何内容。 提高通货膨胀率和通货紧缩率。",
    "Aww man, no narcotic properties?": "哦，伙计，没有麻醉品吗？",
    "Dude, I think I'm getting progressively Higher.": "伙计，我想我越来越高了。",
    "Feel That Superfluidity.": "感受那种超流。",
    "Float.": "漂浮。",
    "Gas Gas Gas.": "气气气。",
    "Going 1355.633077 miles an hour.": "每小时行驶 1355.633077 英里。",
    "I need a new dust filter for my Hoover Max Extract Pressure Pro model 60": "我的 Hoover Max Extract Pressure Pro 60 型需要一个新的滤尘器",
    "Li": "锂",
    "Natural Gas Extraction. (This is a fart joke).": "天然气开采。 （这是一个放屁的笑话）。",
    "Naw man, come on. Don't leave now!": "牛人，来吧。 现在不要离开！",
    "Reduce image scaling.": "减少图像缩放。",
    "Remove the exponent of the Helium effects but unlock more Hydrogen upgrades. Keep Cost.": "移除氦效应的指数，但解锁更多的氢升级。 保持成本。",
    "Softcap Helium boost to Hydrogen Exponged gain starting at 200 Helium.": "从 200 氦 开始，软上限氦 提升到 氢膨胀 增益。",
    "Unlock a multiplier tank but 10x tank capacity. Hydrogen Multiplier starts at 0.1.": "解锁一个乘数坦克，但 10 倍坦克容量。 氢倍增器从 0.1 开始。",
    "Unlock Hydrogen button automation. Gain 1 Helium from Jules Janssen.": "解锁氢气按钮自动化。 从朱尔斯·詹森处获得 1 个氦气。",
    "Unlock Hydrogen tank automation.": "解锁氢罐自动化。",
    "Unlock Lithium. Keep cost.": "解锁锂。 保持成本。",
    "Who's There?": "谁在那儿？",
    "You lose all your Helium. ):": "你失去了所有的氦气。 ):",
    "Unlock balloons. Remove Hydrogen Multiplier Division. The Multiplier also boosts Hydrogen Power. Hydrogen Multiplier falls much slower.": "解锁气球。 删除氢倍增器。 乘数还可以提高氢能。 氢倍增器的下降速度要慢得多。",
    "Damn, you actually managed to get all those rocketship parts. Sadly, that's not the end. Ya gotta go over to the next tab and go build more rocketship's my man! This tab is just for a visiual aid anyway. Go uh, go colonize some planets or something, you're good at that right?": "该死的，你居然设法得到了所有那些火箭飞船的零件。 可悲的是，这还没有结束。 你得去下一个标签，去建造更多的火箭飞船，我的男人！ 无论如何，此选项卡仅用于视觉帮助。 去吧，去殖民一些星球之类的，你很擅长吧？",
    "Uh-oh, seems like society has turned against you. Luckily, Beryllium has many properties that makes it great for manufacturing space craft. First and foremost, ya gotta build the rocketship. (Also it's important to note that layers only reset other layers that are to the left of them.)": "哦，看来社会已经开始反对你了。 幸运的是，铍具有许多特性，使其非常适合制造航天器。 首先，你要建造火箭飞船。 （另外需要注意的是，图层只会重置其左侧的其他图层。）",
    "Abbreviations": "缩写",
    "again": "再次",
    "Are": "是",
    "Are Quizzical": "很奇怪",
    "Beryllium": "铍",
    "Beryllium Scrap to Plate converter's scaling is reset": "铍废料转板转换器的缩放比例已重置",
    "Beryllium Scrap to Plate converter's scaling is reset again. Keep Cost.": "铍废料转板转换器的比例再次重置。保持成本。",
    "Beryllium Scrap to Plate converter's scaling is reset. Keep Cost.": "铍废料转板转换器的比例被重置。保持成本。",
    "BeRyLlIuM ScrAp To PlAtE CoNvErTeR's ScAlInG Is ReSeT. KeEp CoSt.": "铍废料到板转换器的缩放被重置。保持成本。",
    "Beryllium Scraps": "铍废料",
    "Boosts Lithium from Lepoidolite based on total amount of the nozzles and fins per tank.": "根据每个罐的喷嘴和翅片的总量，从锂云石中提升锂。",
    "Brahe": "布拉赫",
    "Convert Beryllium Scraps to Plates using a Industrial Beryllium Plate Rolling Machine.": "使用工业铍板轧机将铍废料转换成板。",
    "Death Star": "死星",
    "Earth": "地球",
    "Gain 1 more Beryllium scrap per casing on reset.": "重置时每个外壳多获得 1 个铍废料。",
    "Galileo": "伽利略",
    "Genviron": "Genviron",
    "Get a foward seperation rocket.": "得到一个前向分离火箭。",
    "Get a fuel tank.": "找个油箱。",
    "Get an outer casing.": "得到一个外壳。",
    "Map": "地图",
    "Mars": "火星",
    "Max rocketships reached.": "最大火箭飞船达到。",
    "Mercury": "汞",
    "MultiOrb": "多球",
    "Must have 0 fuel tanks to buy.": "必须有 0 个油箱才能购买。",
    "Neptune": "海王星",
    "Planet gwa": "格瓦星",
    "Pluto": "冥王星",
    "Put all your rocketships on standby.": "让你所有的火箭飞船待命。",
    "R": "R",
    "Reduce Beryllium cost exponent by 0.4 again. Keep Cost.": "再次将铍成本指数降低 0.4。保持成本。",
    "Reduce Beryllium's cost exponent by 0.4. Keep Cost.": "将铍的成本指数降低 0.4。保持成本。",
    "Reset Tier 1 Resources.": "重置第 1 层资源。",
    "Resources": "资源",
    "Riddle Me": "谜我",
    "Saturn": "土星",
    "Sell One": "卖一",
    "Tests?": "测试？",
    "The Moon": "月亮",
    "The Sun": "太阳",
    "Then": "然后",
    "This Batman": "这个蝙蝠侠",
    "Throw All Beryllium Scrap Back In The Dumpster": "将所有铍废料扔回垃圾箱",
    "Unlock balloons. Remove Hydrogen Multiplier Division. The Multiplier also boosts Hydrogen Power. Hydrogen Multiplier falls much slower.": "解锁气球。删除氢倍增器。乘数还可以提高氢能。氢倍增器的下降速度要慢得多。",
    "Unlock Le Universe": "解锁乐宇宙",
    "Uranus": "天王星",
    "Venus": "金星",
    "What": "什么",
    "Woah who would have guessed, Beryllium Scrap to Plate converter's scaling is reset. Keep Cost.": "哇，谁会猜到，铍废料到板转换器的缩放被重置。保持成本。",
    "Here you will advance from element to element until I decide to stop. That's about it, not much else to say...There's save files under this if you want to skip a section or your savefile gets corrupted. (Mobile players, ya gotta swap over to the low qual mode. Just like, click on the gear thingy.)": "在这里，您将逐个元素前进，直到我决定停止。 就是这样，没什么好说的……如果你想跳过一个部分或者你的保存文件被损坏，下面有保存文件。 （移动玩家，你必须切换到低质量模式。就像，点击齿轮。）",
    "Buy A Better Blade Guard": "购买更好的刀片防护罩",
    "Buyables": "可购买",
    "Enhance Your Blade": "增强你的刀片",
    "Save bank:": "存档银行：",
    "Sharpen Your Blade": "磨砺你的刀片",
    "The Workshop": "工作台",
    "Use A Better Handle": "使用更好的手柄",
    "Nice going. You got the diamond hand saw with ease. Now comes the fun part. Use that saw and start drilling into the meteorites. Remember: The bigger they are, the more abundant they are in Boron.": "好走。 您轻松获得了钻石手锯。 有趣的来了。 用那把锯子开始钻入陨石。 请记住：它们越大，它们在硼中的含量就越丰富。",
    "Add 1 to base of Drilling speed. Add one per upgrade on this row.": "钻孔速度的基础加 1。在此行上每次升级添加一个。",
    "Add 1 to Boron Base. Add one per upgrade on this row.": "向硼碱加 1。在此行上每次升级添加一个。",
    "Add Log2(2) to Boron Base. Add one per upgrade on this row.": "将 Log2(2) 添加到硼基。在此行上每次升级添加一个。",
    "Add the power of 1.5 to the Boron Multiplier.": "将 1.5 的幂添加到硼乘数。",
    "Add the power of 2 to the Boron Multiplier.": "将 2 的幂添加到硼乘数。",
    "Autobuy 1000x more.": "自动购买 1000 倍以上。",
    "Autobuyers autobuy 100x faster.": "自动购买者的自动购买速度提高了 100 倍。",
    "Autobuyers autobuy 10x faster. Keep cost.": "自动购买者的自动购买速度提高了 10 倍。保持成本。",
    "BaD BreakInG": "坏突破",
    "Bonkers Manners": "疯狂的礼仪",
    "Boron +1.07e60": "硼 +1.07e60",
    "Boron Deficiency.": "缺硼。",
    "Boron Multiplier is now 2. Add one per upgrade on this row.": "硼乘数现在为 2。在此行上每次升级添加一个。",
    "Boron-Chelate Complex, Rosocyanine": "硼螯合物，蔷薇花青",
    "Boronated Fiberglass": "硼化玻璃纤维",
    "Borosilicate Glass": "硼硅酸盐玻璃",
    "CLICK TO DRILL.": "点击钻取。",
    "Drill: ON": "钻头：开",
    "Drilling speed is doubled. Add one per upgrade on this row.": "钻孔速度加倍。在此行上每次升级添加一个。",
    "Early Automation": "早期自动化",
    "Enriched Boron": "富硼",
    "Fallacies 101": "谬误101",
    "False Dillema'd": "虚假的迪勒玛",
    "Tank Armor And Bulletproof Vests": "坦克装甲和防弹背心",
    "Tavaborole, A Aminoacyl tRNA Synthetase Inhibitor": "塔瓦波罗，一种氨酰 tRNA 合成酶抑制剂",
    "The bottom row of buyables are more effective and autobuy the bottom row but increase cost scaling of all buyables. Keep cost.": "最下面一行的可购买物品更有效，自动购买最下面一行，但增加了所有可购买物品的成本缩放。保持成本。",
    "The first two buyables are more effective and autobuy the first row.": "前两个可购买更有效，自动购买第一行。",
    "The third buyable is more effective.": "第三个可购买的更有效。",
    "Unlock Boron button automation. Also unlock a buyble per upgrade on this row.": "解锁硼按钮自动化。还可以在此行的每次升级中解锁一个可购买的物品。",
    "Boron": "硼",
    "Prisms": "棱镜",
    "Tier 2 planets start with a base of 10,000.": "2 级行星的基数为 10,000。",
    "Unlock Beryllium button automation.": "解锁铍按钮自动化。",
    "Woah man, that was quite the crash landing! Something must of hit your ship hard. Hey wait, what's that over there? That, you know, that massive crater. Wait, yoooo. There's some meteorite debris over there. Go check that stuff out! We'll get Boron! Actually, first of all, we need to create an electric diamond hand saw. Anyway, do whatever it is you do and when you're ready let's start crafting.": "哇，伙计，那真是迫降！ 一定有什么东西重重地击中了你的船。 嘿等等，那边是什么？ 那个，你知道的，那个巨大的陨石坑。 等等，呜呜。 那里有一些陨石碎片。 去看看那些东西！ 我们会得到硼！ 实际上，首先，我们需要创建一个电动金刚石手锯。 无论如何，做任何你想做的事，当你准备好让我们开始制作。",
    "Playing.": "游戏中。",
    "You died, view the MainTab NOW": "你死了，立即查看主选项卡",
    "100 Levels Job/Skill, muliplier formula is: log1000(Resets) + 1 + Job/Skill / 10": "100级 工作/技能，乘数公式为：log 1000(重置) + 1 + 工作/技能 / 10",
    "ALL YOUR PROGRESS.": "你所有的进度。",
    "Alright, cool, cool, cool. Now, I'm going to need you to get employed in a mining company. Start mining some carbon-rich rock- I mean minerals.": "好吧，酷，酷，酷。 现在，我需要你到一家矿业公司工作。 开始开采一些富含碳的岩石——我是说矿物。",
    "Carbon": "碳",
    "Random Stats That Nobody Cares About (RSTNCA):": "无人关心的随机统计数据 (RSTNCA)：",
    "Restart": "重新开始",
    "This time is for real. No joke, no failure, no choice. I am literaly counting on you here.": "这一次是真的。 没有玩笑，没有失败，没有选择。 我真的在这里指望你。",
    "Total Carbon Fragments:": "总碳碎片：",
    "Total Carbon:": "总碳：",
    "Ya know, sometimes I guess ya just need a bit of motivation. How about this, get through it on this reset or you'll lose": "你知道，有时我猜你只是需要一点动力。 这个怎么样，在这个重置时通过它，否则你会输",
    "You gotta step it up man. This is really dragging and not in a good way. We don't got all day ya know?": "你必须加强它的人。 这真的很拖拉，而且不是很好。 我们没有一整天你知道吗？",
    "Battery": "电池",
    "Boosting Nothing": "什么都没有",
    "Borazine, The Inorganic Benzene.": "环硼氮烷，无机苯。",
    "Days happen every tick now.": "现在每一天都在发生。",
    "Days happen twice as fast and your Nitrogen boosts your Health and Carbon/day.": "日子的发生速度是原来的两倍，您的氮会提高您的健康和碳/天。",
    "Double completion gain. Also, you start playing after Nitrogen reset.": "双倍完成增益。 此外，您在氮气重置后开始播放。",
    "Help": "帮助",
    "Minigame": "小游戏",
    "My Stress Is Relieved": "我的压力得到了缓解",
    "Nitrogen": "氮",
    "Nothing": "无",
    "Organic": "有机",
    "Organic Matter": "有机物",
    "Rapid Decompression": "快速减压",
    "RECHARGE ME.": "给我充电。",
    "Screw You Again": "再次拧你",
    "Shop items costs are divided by 2. Unlock AutoShop (toggle in milestones)": "商店物品成本除以 2。解锁 自动商店（在里程碑中切换）",
    "Thermal Decomposition": "热分解",
    "This one is big, you can't push me over again like last time man. You gotta name like these organic compounds correctly or you won't get any Nitrogen. The more ya get right, the better this will go. So you better guess right.": "这个很大，你不能像上次一样把我推倒。 你必须正确命名这些有机化合物，否则你不会得到任何氮。 你做得越正确，事情就会越好。 所以你最好猜对。",
    "What is this organic chemical compound? Put the answer in the Helium Textbox.": "这种有机化合物是什么？ 将答案放在 氦 文本框中。",
    "What Is Going On?": "到底是怎么回事？",
    "Make a Diamond Saw Blade.": "制作金刚石锯片。",
    "Mature Mode: Disabled": "成熟模式：禁用",
    "Requires:": "要求：",
    "1% increased chance to get Lithium from Lepoidolite per fin.": "每个鳍从锂云母中获得锂的几率提高 1%。",
    "10% more mining speed per nozzle. Cap at 101.": "每个喷嘴的采矿速度提高 10%。 上限为 101。",
    "Get a fin.": "得到一个鳍。",
    "Get an engine nozzle.": "得到一个发动机喷嘴。",
    "1. Identify and count the longest chain of carbon atoms. In this case it is 7. Reminder: ONLY USE LOWERCASE.": "1. 识别并计算最长的碳原子链。 在本例中为 7。 提醒：只能使用小写字母。",
    "2. Name the longest carbon chain. Since the number of carbon atoms in our chain is 7, our corresponding root is hept.": "2. 说出最长的碳链。 由于我们链中的碳原子数是 7，因此我们对应的根是 hept。",
    "3. Find the suffix based on the functional group (a specific group of molecules you can easily spot in a compound). In this chemical compound the functional group alkane is present. We take the suffix of that (-ane) and add it to hept giving us heptane. If it was -ol, it would be heptanol.": "3. 根据官能团查找后缀（您可以在化合物中轻松发现的特定分子组）。 在该化合物中存在官能团烷烃。 我们取那个 (-ane) 的后缀并将它添加到 hept 给我们庚烷。 如果它是-ol，它将是庚醇。",
    "4. Number the longest carbon atom chain by which side aproaches the side group(s) the first. In this case both sides reach the side group on 4. Keep 4- in mind.": "4. 对最先接近侧基的最长碳原子链编号。 在这种情况下，双方都在 4 上到达边组。请记住 4-。",
    "5. Name the side group(s). In this side group, we have a bromine atom bonded to a carbon atom. Check the chart below for the prefixes or suffixes. If there is two identical side groups then put the prefix -di, -tri, ect. Based on this and the previous step we get 4-bromomethyl. Overall, our organic chemical compound is 4-bromomethyl heptane": "5. 命名边组。 在这个侧基中，我们有一个与碳原子键合的溴原子。 查看下表中的前缀或后缀。 如果有两个相同的侧组，则添加前缀 -di、-tri 等。 基于此和上一步，我们得到 4-溴甲基。 总的来说，我们的有机化合物是 4-溴甲基庚烷",
    "6. There is another form of displaying the structure. In the diagram below, the edges/ends of the lines are assumed to be carbon atoms. A bezene ring is the hexagon with three lines in it. Here the organic chemical compound is butyl phenyl ether": "6. 还有另一种显示结构的形式。 在下图中，线的边缘/末端假定为碳原子。 苯环是其中有三行的六边形。 这里的有机化合物是丁基苯基醚",
    "Add 1 to the base that is multiplied by the combo.": "将 1 添加到与组合相乘的基数。",
    "Hover over the lightning bolts before the battery dies to restore the battery's life. Click on the battery to start. (May not work on mobile, I dunno)": "在电池耗尽之前将鼠标悬停在闪电上以恢复电池的使用寿命。 点击电池开始。 （手机可能不行，我不知道）",
    "Keep 100% of combo on failure.": "在失败时保持 100% 的连击。",
    "Keep 50% of combo on failure.": "失败时保持 50% 的连击。",
    "Lower Nitrogen amount lost on failure.": "失败时损失的氮量较低。",
    "Multiply the combo by two.": "将组合乘以 2。",
    "Nitrogen multiplies Nitrogen.": "氮与氮相乘。",
    "Particles: Enabled": "粒子：启用",
    "You'll die at 70 years or when you press D after 30 years, view the MainTab for Updates": "你会在 70 岁时死去，或者当你在 30 年后按 D 时，查看 主标签页 以获取更新",
    "Back for more huh, this one sure is a glutton for punishment.": "回来多点哈，这肯定是个贪吃的惩罚。",
    "Bad Manners": "坏习惯",
    "Drill: OFF": "钻头：关",
    "Keep going, Nitrogen awaits.": "继续前进，氮气等待。",
    "Meteorite size: 10 cm.": "陨石尺寸：10厘米。",
    "Ok, wow. Screw you too. What are you going do to then? Rob a bank? Heh, get a load of this guy. Ok fine, we'll go with your plan, genius. Go rob a bank.": "好的，哇。 也搞你。 那你打算怎么办？ 抢银行？ 呵呵，收拾一下这个人。 好吧好吧，我们会按照你的计划去做，天才。 去抢银行。",
    "MC = Metallic Core, SA = Sulfuric Acid, BR = Basalt Rock, He = Helium, SB = Solar Bar, MG = Methane Gas, AG = Ammonia Gas, SL = Slush.": "MC = 金属芯，SA = 硫酸，BR = 玄武岩，He = 氦，SB = 太阳棒，MG = 甲烷气，AG = 氨气，SL = 雪泥。",
    "MLI = Molten Liquid Iron,  PL = Plutonium, SE = Solar Essence, CL = Cloud, IC = Ice, H2O = Water, CA = Carbon.": "MLI = 熔融液态铁，PL = 钚，SE = 太阳精华，CL = 云，IC = 冰，H2O = 水，CA = 碳。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "______________________________Luna County______________________________": "______________________________月神县______________________________",
    "______________________________Thacker Pass______________________________": "______________________________萨克山口______________________________",
    "______________________________Gaston County______________________________": "______________________________加斯顿县______________________________",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "i": "i",
    "g": "g",
    "Ex": "Ex",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Hydrogen increases Hydrogen Power gain by ": "氢增加氢能增益 ",
    "Helium boosts Hydrogen Power and Hydrogen Gas gain by ": "氦可以提高氢能和氢气增益 ",
    ". Max: ": ". 最大: ",
    "Current chance: ": "当前几率：",
    "Lithium boosts Helium Expunged and Hydrogen Gas + Power gain by ": "锂使氦气排出和氢气+功率增益提高 ",
    "Your mining speed is ": "你的挖矿速度是 ",
    "Boron +": "硼 +",
    "Total Days: ": "总天数：",
    "Total Years: ": "总年数：",
    "Total Resets: ": "总重置数：",
    "Nitrogen -": "氮 -",
    "Conversion: ": "转换：",
    "Helium also boosts Helium Expunged gain by adding ": "氦气还提高氦排放增益增加 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Rating:": "评分：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^3g PL \+ 1 LI \+ 1L HeH \+ 1 UN \+ 1 WC \+ 1 DI \+ 1,000,000 gwa \+ 10,000,000 LA \+ 1e16 DR \+ 10,000 EG\|\| ([\d\.,]+)$/,
    /^([\d\.,]+) \|\| ([\d\.,]+)$/,
    /^([\d\.,]+) \+ ([\d\.,]+) MC \|\| ([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) achievements$/, '您有 $1 项成就'],
    [/^You have (.+) Beryllium Plates$/, '您有 $1 铍板'],
    [/^You have (.+) Helium Gas$/, '您有 $1 氦气'],
    [/^You have (.+) Helium Gas Expunged$/, '您有 $1 氦气排放'],
    [/^You have (.+) Lithium$/, '您有 $1 锂'],
    [/^You have (.+) Slush.$/, '您有 $1 雪泥。'],
    [/^You have (.+) Dirt.$/, '您有 $1 泥土。'],
    [/^You have (.+) eggs.$/, '您有 $1 蛋。'],
    [/^You have (.+) Mars Dust.$/, '您有 $1 火星尘。'],
    [/^You have (.+) Mercury Dust.$/, '您有 $1 汞尘。'],
    [/^You have (.+) Moon Dust.$/, '您有 $1 月尘。'],
    [/^You have (.+) Venus Dust.$/, '您有 $1 金星尘。'],
    [/^You have (.+) Clouds.$/, '您有 $1 云。'],
    [/^You have (.+) Lasers.$/, '您有 $1 激光。'],
    [/^You have (.+) Ice.$/, '您有 $1 冰。'],
    [/^You have (.+) Solar Bars.$/, '您有 $1 太阳能棒。'],
    [/^You have (.+) Metallic Cores.$/, '您有 $1 金属芯。'],
    [/^You have (.+) Basalt Rocks.$/, '您有 $1 玄武岩。'],
    [/^You have (.+) Solar Essence.$/, '您有 $1 太阳精华。'],
    [/^You have (.+) gwa.$/, '您有 $1 gwa。'],
    [/^You have (.+) of Methane Gas.$/, '您有 $1 甲烷气体。'],
    [/^You have (.+) of Water.$/, '您有 $1 水。'],
    [/^You have (.+) of Hydrogen.$/, '您有 $1 氢。'],
    [/^You have (.+) of Ammonia Gas.$/, '您有 $1 氨气。'],
    [/^You have (.+) of Carbon.$/, '您有 $1 碳。'],
    [/^You have (.+) of Helium.$/, '您有 $1 氦。'],
    [/^You have (.+) of Molten Liquid Iron.$/, '您有 $1 熔化的液态铁。'],
    [/^You have (.+) of Sulfuric Acid.$/, '您有 $1 硫酸。'],
    [/^Drilling through (.+) Ticks\/tick$/, '钻穿 $1 Ticks\/tick'],
    [/^Making (.+) Eggs\/tick.$/, '制作 $1 鸡蛋\/tick。'],
    [/^Making (.+) Dirt\/tick.$/, '制作 $1 泥土\/tick。'],
    [/^Making (.+) Lasers\/tick.$/, '制作 $1 激光\/tick。'],
    [/^Making (.+) gwa\/tick.$/, '制作 $1 gwa\/tick。'],
    [/^Have (.+) Nitrogen$/, '有 $1 氮'],
    [/^You have (.+) completon(s) and need (.+) of all Jobs and Skills for (.+) more completion\(s\).$/, '您有 $1 完成，需要 $2 个所有工作和技能才能再完成 $3 次。'],
    [/^You have done (.+) Boron Resets$/, '你已经完成了 $1 次硼重置'],
    [/^You have (.+) of Boron from meteorites.$/, '你有 $1 来自陨石的 硼。'],
    [/^You have (.+) completion$/, '你有 $1 已完成'],
    [/^You have (.+) Hydrogen Power$/, '你有 $1 氢能'],
    [/^You have (.+) Hydrogen Gas$/, '您有 $1 氢气'],
    [/^(.+)Misc(.+)Active(.+)Effect(.+)Carbon\/day(.+)$/, '$1杂项$2激活$3效果$4碳\/天$5'],
    [/^(.+)Properties(.+)Active(.+)Effect(.+)Carbon\/day(.+)$/, '$1属性$2激活$3效果$4碳\/天$5'],
    [/^You are making (.+) Hydrogen Gas per tick$/, '您每 tick 生产 $1 氢气'],
    [/^You have (.+) of Francium from Lepoidolite.$/, '你有 0.00 克来自锂云石的钫。'],
    [/^You have (.+) of Ultra Lithium from Lepoidolite.$/, '您有 0.00 克来自锂云石的超锂。'],
    [/^You have (.+) of Potassium from Lepoidolite \(2x Lithium per g\).$/, '您有 $1 克来自锂云石的钾（每克 2 倍锂）。'],
    [/^You have (.+) of Hydroxide from Lepoidolite \(2x Rubidium per L\).$/, '您有来自锂云石的 $1 氢氧化物（每升 2x 铷）。'],
    [/^You have (.+) of Hydrogen from Lepoidolite \(10% more Lithium per L\).$/, '你有 $1 来自锂云石的氢气（每升 10% 的锂）。'],
    [/^You have (.+) of Fluorine from Lepoidolite.$/, '您有 $1 来自 Lepoidolite 的氟。'],
    [/^You have (.+) of Silicon from Lepoidolite.$/, '您有 $1 来自锂云石的硅。'],
    [/^You have (.+) of Rubidium from Lepoidolite \(20% more Lithium and Hydrogen per g\).$/, '你有 $1 来自锂云石的铷（每克锂和氢增加 20%）。'],
    [/^You have (.+) of Aluminum from Lepoidolite \(10x Potassium and Hydroxide per g\).$/, '您有 $1 来自锂云石的铝（每克 10 倍钾和氢氧化物）。'],
    [/^You have (.+) of Lithium from Lepoidolite \(Currency\).$/, '你有 $1 锂云石（货币）。'],
    [/^Current Effect: (.+) to Boron Multiplier before other effects$/, '当前效果：$1 到其他效果之前的硼倍增器'],
    [/^Current Effect: (.+) to Boron Multiplier$/, '当前效果：$1 到硼倍增器'],
    [/^Current Effect: (.+) to base of Drilling Speed$/, '当前效果：$1 到基础钻孔速度'],
    [/^Current Effect: (.+) to \"Enhance Your Blade\"$/, '当前效果：$1 到“增强你的刀片”'],
    [/^Time until finished drilling: (.+) ticks. Reward: (.+) of Boron.$/, '直到完成钻孔的时间：$1 tick。 奖励：$2 硼。'],
    [/^You are (.+) ticks into the run.$/, '你有 $1 tick 在此运行。'],
    [/^Reset for (.+) Beryllium Scraps$/, '重置为 $1 铍废料'],
    [/^Have a combo of (.+)$/, '有 $1 个组合'],
    [/^Next at (.+) Rainbownium$/, '下一个在 $1 彩虹'],
    [/^Next at (.+) completion\(s\)$/, '下一个在 $1 完成'],
    [/^You have made a total of (.+) Nitrogen and have done (.+) Nitrogen resets.$/, '您总共制作了 $1 氮并进行了 $2 次氮重置。'],
    [/^Your Total Nitrogen is multiplying Carbon\/day by (.+) and your Health by (.+)$/, '您的总氮将每天的碳乘以 $1，您的健康乘以 $2'],
    [/^(.+) Carbon and (.+) Carbon Fragments.$/, '$1 碳和 $2 碳碎片。'],
    [/^Level: (.+). Highest Level: (.+)$/, '等级：$1。最高等级：$2'],
    [/^Lose (.+) Nitrogen on failure.$/, '失败时损失 $1 氮。'],
    [/^Prisms boosts all Beryllium resources by (.+). Cost scales at (.+) rainbownium.$/, '棱镜将所有铍资源提升 $1。 成本为 $2 彩虹年。'],
    [/^(.+) of Helium Hydride$/, '$1 氢化氦'],
    [/^(.+)Basics$/, '$1基础'],
    [/^(.+)Thief$/, '$1盗贼'],
    [/^(.+)Training$/, '$1训练'],
    [/^(.+)Mining(.+)Company$/, '$1矿业公司'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Next at (.+) Hydrogen$/, '下一个在 $1 氢'],
    [/^You have done (.+) resets$/, '您已完成 $1 次重置'],
	[/^([\d\.]+)m ([\d\.]+)s$/, '$1分 $2秒'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\-([\d\.]+) Health$/, '\-$1 生命值'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.]+)e([\d\.,]+) Lithium$/, '$1e$2 锂'],
    [/^([\d\.]+)e([\d\.,]+) Helium$/, '$1e$2 氦'],
    [/^([\d\.]+)e([\d\.,]+) Rainbownium$/, '$1e$2 彩虹'],
    [/^([\d\.]+)e([\d\.,]+)g of Plutonium$/, '$1e$2 克 钚'],
    [/^([\d\.,]+) \/ ([\d\.]+) Hydrogen Power$/, '$1 \/ $2 氢能'],
    [/^([\d\.,]+) \/ ([\d\.,]+) Hydrogen Power$/, '$1 \/ $2 氢能'],
    [/^([\d\.,]+) Achievements$/, '$1 成就'],
    [/^([\d\.,]+) Boron Reset$/, '$1 硼重置'],
    [/^([\d\.,]+) Boron Resets$/, '$1 硼重置'],
    [/^([\d\.,]+) Lithium Reset$/, '$1 锂重置'],
    [/^([\d\.,]+) Lithium Resets$/, '$1 锂重置'],
    [/^([\d\.,]+) Cancri A$/, '$1 巨蟹座 A'],
    [/^([\d\.,]+)  Nitrogen$/, '$1 氮'],
    [/^([\d\.,]+) Water Clouds$/, '$1 水云'],
    [/^([\d\.,]+) Diamonds$/, '$1 钻石'],
    [/^([\d\.,]+) Light$/, '$1 光'],
    [/^([\d\.,]+) Unknown$/, '$1 未知'],
    [/^([\d\.,]+) Helium$/, '$1 氦'],
    [/^([\d\.,]+) Total Helium$/, '总计 $1 氦'],
    [/^([\d\.,]+) Beryllium Scrap$/, '$1 铍废料'],
    [/^([\d\.,]+) Nitrogen Resets$/, '$1 氮重置'],
    [/^([\d\.,]+) Boron Reset$/, '$1 硼重置'],
    [/^([\d\.,]+) Total Nitrogen$/, '总计 $1 氮'],
    [/^([\d\.,]+) Nitrogen$/, '$1 氮'],
    [/^([\d\.,]+)  Prisms$/, '$1 棱镜'],
    [/^([\d\.,]+) Beryllium Scraps$/, '$1 铍废料'],
    [/^([\d\.,]+) Hydrogen$/, '$1 氢'],
    [/^(.+) Diamonds, (.+) Metallic Cores, (.+) Basalt Rocks and (.+) Prisms.$/, '$1 钻石、$2 金属核心、$3 玄武岩和 $4 棱镜。'],
    [/^([\d\.,]+) Hydrogen and ([\d\.,]+) Hydrogen Power$/, '$1 氢 和 $2 氢能'],
    [/^([\d\.,]+) Carbon and ([\d\.,]+) Carbon Fragments.$/, '$1 碳 和 $2 碳碎片。'],
    [/^([\d\.,]+)x Hydogen Gas.$/, '$1 氢气。'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^(.+) Hydrogen and (.+) Hydrogen Power$/, '$1 氢 和 $2 氢能'],
    [/^Current Combo: x(.+). Current Nitrogen: (.+). Failed: (.+)$/, '当前组合：x$1。 当前氮：$2。 失败：$3'],
    [/^Currently: (.+)x$/, '当前：$1x'],
    [/^Currently: x(.+)$/, '当前：x$1'],
    [/^Year: (.+) Day: (.+)$/, '年: $1 天: $2'],
    [/^Max: (.+)$/, '最大：$1'],
    [/^Cost: (.+) Hydrogen$/, '成本：$1 氢'],
    [/^Cost: (.+) Nitrogen$/, '成本：$1 氮'],
    [/^Cost: (.+) Boron$/, '成本：$1 硼'],
    [/^Cost: (.+) Drilling Speed$/, '成本：$1 钻孔速度'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Cost: (.+) Scraps of Beryllium$/, '成本：$1 铍废料'],
    [/^Cost: (.+) Plates of Beryllium$/, '成本：$1 铍板'],
    [/^Cost: (.+) Beryllium Scraps$/, '成本：$1 铍废料'],
    [/^Cost: (.+) Helium$/, '成本：$1 氦'],
    [/^Cost: (.+) Helium Gas Expunged$/, '成本：$1 氦气排出'],
    [/^Cost: (.+) of Lithium$/, '成本：$1 锂'],
    [/^Cost: (.+) of Boron$/, '成本：$1 硼'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) Hydrogen Power$/, '要求：$1 \/ $2 氢能'],
    [/^Next: (.+) \/ (.+) Hydrogen Power$/, '下一个：$1 \/ $2 氢能'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Req: (.+) \/ (.+)$/, '要求：$1 \/ $2'],
    [/^Amount: (.+) \/ (.+)$/, '数量：$1 \/ $2'],
    [/^Amount: (.+)e(.+)$/, '数量：$1e$2'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);